# 负责检查pull reqests里html文件的links是否都有效
name: Check HTML Links
# 触发 workflow 的事件
on:
  # 有pull request时触发
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
  push:
  workflow_dispatch:

jobs:
  Check-HTML-Links:
    runs-on: windows-2019
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      # 检出代码
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Check links...
        run: |
          cd tools/Check-Links
          pip install -r checkLinks-requirements.txt
          python checkLinks.py

      - name: Check if links are OK...
        id: errors
        uses: juliangruber/read-file-action@v1
        with:
          path: ./checkLinks.md

      - name: Echo bad links...
        run: echo "${{ steps.errors.outputs.content }}"

      - if: steps.errors.outputs.content != '' && github.event_name == 'pull_request'
        name: Comment on PR
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const github = require('@actions/github');
            const { data: pullRequest } = await github.pulls.get({
              owner: github.context.repo.owner,
              repo: github.context.repo.repo,
              pull_number: github.context.payload.pull_request.number
            });
            const commentBody = '# HTML Links Test Report\n\nHi there!\n\nThank you for your Pull Request! However, we regret to inform you that the following illegal relative connection still exists within your Pull Request:\n\n' + steps.errors.outputs.content + '\n\nPlease fix these errors. Thank you again for your contribution.\n\nBegonia/Yuba';
            await github.issues.createComment({
              owner: github.context.repo.owner,
              repo: github.context.repo.repo,
              issue_number: pullRequest.number,
              body: commentBody
            });

      - if: steps.errors.outputs.content != ''
        run: |
          stopMarker=$(uuidgen)
          echo "::$stopMarker::"
