# 负责检查pull reqests里html文件的Link是否都有效
name: Check HTML Links
# 触发 workflow 的事件
on:
  # 有pull request时触发
  pull_request:

  workflow_dispatch:

jobs:
  check-HTML-Links:
    runs-on: windows-2019
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      # 检出代码
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Check Links...
        run: |
          cd tools/checkLinks
          pip install -r checkLinks-requirements.txt
          python checkLinks.py

      - name: Check if links are OK...
        id: errors
        uses: juliangruber/read-file-action@v1
        with:
          path: ./checkLinks.md
      - name: Echo Bad Links...
        run: echo "${{ steps.errors.outputs.content }}"

      - if: steps.errors.outputs.content != ''
        run: |
          stopMarker=$(uuidgen)
          echo "::$stopMarker::"
